### ISSUE TITLE
Enable custom colors in menu items

### ISSUE THREAD

**Issue by stdedos** [pmbarrett314/curses-menu#32] opened 2017-10-04 11:57 UTC
Maybe it would be useful to refactor this code (and item instance) to enable custom text format?

https://github.com/pmbarrett314/curses-menu/blob/c76fc00ab9d518eab275e55434fc2941f49c6b30/cursesmenu/curses_menu.py#L206-L211

**Comment by pmbarrett314** [comment] 2022-08-01 07:06
Closing as duplicate of #16

**Closed by pmbarrett314** 2022-08-01 07:06 UTC
Labels: enhancement
